### ISSUE TITLE
Frame count and width

### ISSUE THREAD

**Issue by yasinkacmaz** [deepaktwr/BitFrames#2]
How can we beat the 4 frame limit, for instance I want to show 30 images. Also how can we oppucy all screen width. Here is the screenshot :

![device-2016-10-08-025650](https://cloud.githubusercontent.com/assets/14234610/19212411/4f5adcd2-8d59-11e6-8ae0-9f9755402418.png)

My code :

`<proj.me.bitframe.ViewFrame
        android:id="@+id/view_frame"
        xmlns:frame="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        frame:maxFrameCount="15"
        android:layout_height="wrap_content"/>`

**Comment by deepaktwr** [comment]
Hi Yasin,
The frame only supports max 4 frame count for now, which will have 5 in future releases.
You may prefer using GridView if you want 32 images in a frame.

for full screen width you may consider using:

`ViewFrame viewFrame = (ViewFrame)findViewById(R.id.view_frame);`

`viewFrame.setFrameDimensions(float minFrameWidth, float minFrameHeight, float maxContainerWidth, float maxContainerHeight);`

you may pass all 0's in setFrameDimensions, it'll calculate width and height based on density pixels.
Or provide full width and height by calculating from

`int widthPixels = getResources().getDisplayMetrics().widthPixels;`
 `int heightPixels = getResources().getDisplayMetrics().heightPixels;`

and passing min and max dimensions accordingly in setFrameDimensions.

for fixed width and height dimensions in which container width and height will be fixed regardless the image dimensions use:

`frame:hasFixedDimensions` to true
or
`viewFrame.setHasFixedDimension(true);`

**Comment by yasinkacmaz** [comment]
Thanks for reply, I will try this and let you know

**Comment by deepaktwr** [comment]
[this](https://github.com/lucasr/twoway-view) may solve your problem.
